### ISSUE TITLE
Couldn't find a configuration settings named "registry"

### ISSUE THREAD

**Issue by gqzcl** [vuepress/vp-update#4]
when I use ` yarn dlx vp-update` to update vuepress，it said  'Couldn't find a configuration settings named "registry"'
the version of yarn is:
```
3.6.3
```
and the error as follow:
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 25s 652ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ rxjs@npm:7.8.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ tmp@npm:0.0.33 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ type-fest@npm:0.21.3 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ vp-update@npm:0.2.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ wcwidth@npm:1.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0000: └ Completed in 1s 105ms
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed
➤ YN0000: Done with warnings in 26s 833ms

Upgrading current project...
file:///root/.yarn/berry/cache/execa-npm-7.2.0-7797cafb24-8.zip/node_modules/execa/lib/error.js:60
                error = new Error(message);
                        ^

Error: Command failed with exit code 1: yarn config get registry
Usage Error: Couldn't find a configuration settings named "registry"

$ yarn config get [--json] [--no-redacted] <name>
    at makeError (file:///root/.yarn/berry/cache/execa-npm-7.2.0-7797cafb24-8.zip/node_modules/execa/lib/error.js:60:11)
    at execaSync (file:///root/.yarn/berry/cache/execa-npm-7.2.0-7797cafb24-8.zip/node_modules/execa/index.js:201:17)
    at execaCommandSync (file:///root/.yarn/berry/cache/execa-npm-7.2.0-7797cafb24-8.zip/node_modules/execa/index.js:276:9)
    at O (file:///root/.yarn/berry/cache/vp-update-npm-0.2.0-57fd61b50e-8.zip/node_modules/vp-update/lib/index.js:2:1448)
    at U (file:///root/.yarn/berry/cache/vp-update-npm-0.2.0-57fd61b50e-8.zip/node_modules/vp-update/lib/index.js:2:1499)
    at CAC.<anonymous> (file:///root/.yarn/berry/cache/vp-update-npm-0.2.0-57fd61b50e-8.zip/node_modules/vp-update/lib/index.js:3:605)
    at CAC.runMatchedCommand (file:///root/.yarn/berry/cache/cac-npm-6.7.14-c46284e425-8.zip/node_modules/cac/dist/index.mjs:610:34)
    at CAC.parse (file:///root/.yarn/berry/cache/cac-npm-6.7.14-c46284e425-8.zip/node_modules/cac/dist/index.mjs:537:12)
    at file:///root/.yarn/berry/cache/vp-update-npm-0.2.0-57fd61b50e-8.zip/node_modules/vp-update/lib/index.js:4:319
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  shortMessage: 'Command failed with exit code 1: yarn config get registry',
  command: 'yarn config get registry',
  escapedCommand: 'yarn config get registry',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: `\x1B[31m\x1B[1mUsage Error\x1B[22m\x1B[39m: Couldn't find a configuration settings named "registry"\n` +
    '\n' +
    '\x1B[1m$ \x1B[22myarn config get [--json] [--no-redacted] <name>',
  stderr: '',
  cwd: '/root/code/vuepress-blog',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Node.js v18.16.1
```
After I mondify the `yarn config get registry` to `yarn config get npmRegistryServer` in vp-update-npm-0.2.0-57fd61b50e-8.zip，It can work success。
my yarn config as follow:
```
➤ YN0000: npmPublishAccess              null
➤ YN0000: npmPublishRegistry            null
➤ YN0000: npmRegistries                 Map(0) {}
➤ YN0000: npmRegistryServer             'https://registry.npmmirror.com/'
➤ YN0000: npmScopes                     Map(0) {}
➤ YN0000: packageExtensions             Map(0) {}
```

**Comment by Mister-Hope** [comment]
Fixed, sorry for the delay
